---
- name: setup webserver
  hosts: all
  become: true
  tasks:
    - name: httpd installed
      yum:
        name: httpd
        state: latest
    - name: httpd service start
      service:
        name: httpd
        state: started
    - name: copy index.html
      copy:
        src: /opt/index.html
        dest: /var/www/html
    - name: httpd service restart
      service:
        name: httpd
        state: restarted
